// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAsyGYt9I6alcmlQ1qVyllo950BkioYk',
    appId: '1:302663571613:web:bd344e6b8c1b5caacadc74',
    messagingSenderId: '302663571613',
    projectId: 'fir-crud-598b1',
    authDomain: 'fir-crud-598b1.firebaseapp.com',
    storageBucket: 'fir-crud-598b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMV-ITG1QAceJQfjwNoDEdwZR8heXLg9w',
    appId: '1:302663571613:android:b1e350dacf76e85bcadc74',
    messagingSenderId: '302663571613',
    projectId: 'fir-crud-598b1',
    storageBucket: 'fir-crud-598b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIt59kwD7WWpiLzMk5gwkxOCCIkOeGmYk',
    appId: '1:302663571613:ios:bdb114b879e91d5dcadc74',
    messagingSenderId: '302663571613',
    projectId: 'fir-crud-598b1',
    storageBucket: 'fir-crud-598b1.appspot.com',
    iosClientId: '302663571613-77r0f9rtet1rm5tp7gum4t30m7fg87q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIt59kwD7WWpiLzMk5gwkxOCCIkOeGmYk',
    appId: '1:302663571613:ios:bdb114b879e91d5dcadc74',
    messagingSenderId: '302663571613',
    projectId: 'fir-crud-598b1',
    storageBucket: 'fir-crud-598b1.appspot.com',
    iosClientId: '302663571613-77r0f9rtet1rm5tp7gum4t30m7fg87q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
